function fig_hdl = GUI_ACC_build
%
% Graphical User Interface (GUI) for the prediction of Axial Compression
% Capacity (ACC) of Concrete Filled Double Skin Steel Tubes (CFDST) columns
%
% Description:
% In this GUI, two ANNs are used for the prediction of axial compression
% capacity of CFDST columns. These ANNs have resulted from training based
% on experimental data, and have been trained with two optimization
% algorithms (Artificial Bee Colony, ABC, and Teaching-Learning Based
% Optimization, TLBO). One algorithm is used for training of each ANN.
% In the input parameters panel, the user can input the various
% characteristics of the CFDST column and in the output panel, by clicking
% the 'Predict (TLBO-ANN)' button for application of the ANN optimized by
% the TLBO-ANN algorithm, and the 'Predict (ABC-ANN)' button for
% application of the ANN optimized by the ABC-ANN algorithm, the predictive
% results of axial compression capacity of CFDST columns are displayed
% directly.
%


% Initialize handles structure
handles = struct();

% Create all UI controls
build_gui();

% Assign function output
fig_hdl = handles.figure1;

%% ------------------------------------------------------------------------
    function build_gui()
        % Creation of all uicontrols
        
        % --- FIGURE -------------------------------------
        handles.figure1 = figure( ...
            'Tag', 'figure1', ...
            'Units', 'characters', ...
            'Position', [136 15 171 48], ...
            'Name', 'GUI_ACC', ...
            'MenuBar', 'none', ...
            'NumberTitle', 'off', ...
            'Color', [0.94 0.94 0.94]);
        
        % --- PANELS -------------------------------------
        handles.uipanel1 = uipanel( ...
            ...'Parent', handles.figure1, ...
            'Tag', 'uipanel1', ...
            'Units', 'characters', ...
            'Position', [93 17.5 77 27], ...
            'FontName', 'Times New Roman', ...
            'FontSize', 14, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', [0 0.451 0.741], ...
            'Title', 'Input parameters', ...
            'ShadowColor', [0.7 0.7 0.7]);
        
        handles.uipanel2 = uipanel( ...
            ...'Parent', handles.figure1, ...
            'Tag', 'uipanel2', ...
            'Units', 'characters', ...
            'Position', [93 1 77 15.5], ...
            'FontName', 'Times New Roman', ...
            'FontSize', 14, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', [0 0.451 0.741], ...
            'Title', 'Output parameter', ...
            'ShadowColor', [0.7 0.7 0.7]);
        
        % --- AXES -------------------------------------
        handles.axes1 = axes( ...
            'Parent', handles.figure1, ...
            'Tag', 'axes1', ...
            'Visible', 'off', ...
            'Units', 'characters', ...
            'Position', [2 1 89.2 36.6153846153846]);
        
        % --- STATIC TEXTS -------------------------------------
        handles.text3 = uicontrol( ...
            'Parent', handles.uipanel1, ...
            'Tag', 'text3', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', [1 22 66 1.6], ...
            'FontName', 'Times New Roman', ...
            'FontSize', 14, ...
            'String', 'Column length, L (mm)', ...
            'HorizontalAlignment', 'left');
        
        handles.text4 = uicontrol( ...
            'Parent', handles.uipanel1, ...
            'Tag', 'text4', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', [1 19 66 1.6], ...
            'FontName', 'Times New Roman', ...
            'FontSize', 14, ...
            'String', 'Ratio Di/Do', ...
            'HorizontalAlignment', 'left');
        
        handles.text5 = uicontrol( ...
            'Parent', handles.uipanel1, ...
            'Tag', 'text5', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', [1 16 66 1.6], ...
            'FontName', 'Times New Roman', ...
            'FontSize', 14, ...
            'String', 'Ratio ti/to', ...
            'HorizontalAlignment', 'left');
        
        handles.text24 = uicontrol( ...
            'Parent', handles.uipanel1, ...
            'Tag', 'text24', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', [1 13 66 1.6], ...
            'FontName', 'Times New Roman', ...
            'FontSize', 14, ...
            'String', 'Inner steel tube diameter, Di (mm)', ...
            'HorizontalAlignment', 'left');
        
        handles.text25 = uicontrol( ...
            'Parent', handles.uipanel1, ...
            'Tag', 'text25', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', [1 10 66 1.6], ...
            'FontName', 'Times New Roman', ...
            'FontSize', 14, ...
            'String', 'Inner steel tube thickness, ti (mm)', ...
            'HorizontalAlignment', 'left');
        
        handles.text6 = uicontrol( ...
            'Parent', handles.uipanel1, ...
            'Tag', 'text6', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', [1 7 66 1.6], ...
            'FontName', 'Times New Roman', ...
            'FontSize', 14, ...
            'String', 'Outer steel tube strength, fyo (MPa)', ...
            'HorizontalAlignment', 'left');
        
        handles.text7 = uicontrol( ...
            'Parent', handles.uipanel1, ...
            'Tag', 'text7', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', [1 4 66 1.6], ...
            'FontName', 'Times New Roman', ...
            'FontSize', 14, ...
            'String', 'Inner steel tube strength, fyi (MPa)', ...
            'HorizontalAlignment', 'left');
        
        handles.text8 = uicontrol( ...
            'Parent', handles.uipanel1, ...
            'Tag', 'text8', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', [1 1 66 1.6], ...
            'FontName', 'Times New Roman', ...
            'FontSize', 14, ...
            'String', 'Concrete compressive strength, f''c (MPa)', ...
            'HorizontalAlignment', 'left');
        
        handles.text9 = uicontrol( ...
            'Parent', handles.uipanel2, ...
            'Tag', 'text9', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', [1 11.5 59.4 1.6], ...
            'FontName', 'Times New Roman', ...
            'FontSize', 14, ...
            'String', 'Axial Compression Capacity, Pu (kN)', ...
            'HorizontalAlignment', 'left');
        
        handles.text15 = uicontrol( ...
            'Parent', handles.uipanel2, ...
            'Tag', 'text15', ...
            'UserData', zeros(1,0), ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', [1.4 4.92307692307692 66 1.15384615384615], ...
            'FontName', 'Times New Roman', ...
            'FontSize', 10, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', [0.471 0.671 0.188], ...
            'String', 'This GUI is developed by Dr. G. Papazafeiropoulos', ...
            'HorizontalAlignment', 'left');
        
        handles.text16 = uicontrol( ...
            'Parent', handles.uipanel2, ...
            'Tag', 'text16', ...
            'UserData', zeros(1,0), ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', [1.4 2.69230769230769 66 1.15384615384615], ...
            'FontName', 'Times New Roman', ...
            'FontSize', 10, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', [0.471 0.671 0.188], ...
            'String', 'School of Civil Engineering, National Technical University of Athens', ...
            'HorizontalAlignment', 'left');
        
        handles.text17 = uicontrol( ...
            'Parent', handles.uipanel2, ...
            'Tag', 'text17', ...
            'UserData', zeros(1,0), ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', [1.4 0.461538461538462 66 1.15384615384615], ...
            'FontName', 'Times New Roman', ...
            'FontSize', 10, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', [0.471 0.671 0.188], ...
            'String', 'E-mail: gpapazafeiropoulos@yahoo.gr', ...
            'HorizontalAlignment', 'left');
        
        % --- PUSHBUTTONS -------------------------------------
        handles.Prediction = uicontrol( ...
            'Parent', handles.uipanel2, ...
            'Tag', 'Prediction', ...
            'Style', 'pushbutton', ...
            'Units', 'characters', ...
            'Position', [1.4 6.5 32 2.53846153846154], ...
            'FontName', 'Times New Roman', ...
            'FontSize', 12, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', [1 0 0], ...
            'String', 'Predict (ABC-ANN)', ...
            'Callback', @Prediction_ABC_ANN_Callback);
        
        handles.Prediction = uicontrol( ...
            'Parent', handles.uipanel2, ...
            'Tag', 'Prediction', ...
            'Style', 'pushbutton', ...
            'Units', 'characters', ...
            'Position', [35 6.5 32 2.53846153846154], ...
            'FontName', 'Times New Roman', ...
            'FontSize', 12, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', [1 0 0], ...
            'String', 'Predict (TLBO-ANN)', ...
            'Callback', @Prediction_TLBO_ANN_Callback);
        
        % --- EDIT TEXTS -------------------------------------
        handles.edit1 = uicontrol( ...
            'Parent', handles.figure1, ...
            'Tag', 'edit1', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', [0 45 171 3], ...
            'FontName', 'Times New Roman', ...
            'FontSize', 14, ...
            'FontWeight', 'bold', ...
            'ForegroundColor', [0 0.451 0.741], ...
            'BackgroundColor', [0.922 0.522 0.349], ...
            'String', 'Graphical User Interface (GUI) for prediction of ACC of CFDST columns', ...
            'Callback', @edit1_Callback, ...
            'CreateFcn', @edit1_CreateFcn);
        
        handles.editL = uicontrol( ...
            'Parent', handles.uipanel1, ...
            'Tag', 'editL', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', [64 22 11 1.61538461538462], ...
            'FontName', 'Times New Roman', ...
            'FontSize', 12, ...
            'BackgroundColor', [1 1 1], ...
            'String', '230.0', ...
            'Callback', @editL_Callback, ...
            'CreateFcn', @editL_CreateFcn);
        
        handles.editDiDo = uicontrol( ...
            'Parent', handles.uipanel1, ...
            'Tag', 'editDiDo', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', [64 19 11 1.61538461538461], ...
            'FontName', 'Times New Roman', ...
            'FontSize', 12, ...
            'BackgroundColor', [1 1 1], ...
            'String', '0.8316', ...
            'Callback', @editDiDo_Callback, ...
            'CreateFcn', @editDiDo_CreateFcn);
        
        handles.edittito = uicontrol( ...
            'Parent', handles.uipanel1, ...
            'Tag', 'edittito', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', [64 16 11 1.61538461538461], ...
            'FontName', 'Times New Roman', ...
            'FontSize', 12, ...
            'BackgroundColor', [1 1 1], ...
            'String', '0.9535', ...
            'Callback', @edittito_Callback, ...
            'CreateFcn', @edittito_CreateFcn);
        
        handles.editDi = uicontrol( ...
            'Parent', handles.uipanel1, ...
            'Tag', 'editDi', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', [64 13 11 1.61538461538461], ... %%%
            'FontName', 'Times New Roman', ...
            'FontSize', 12, ...
            'BackgroundColor', [1 1 1], ...
            'String', '62.70', ...
            'Callback', @editDi_Callback, ...
            'CreateFcn', @editDi_CreateFcn);
        
        handles.editti = uicontrol( ...
            'Parent', handles.uipanel1, ...
            'Tag', 'editti', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', [64 10 11 1.61538461538461], ... %%%
            'FontName', 'Times New Roman', ...
            'FontSize', 12, ...
            'BackgroundColor', [1 1 1], ...
            'String', '1.23', ...
            'Callback', @editti_Callback, ...
            'CreateFcn', @editti_CreateFcn);
        
        handles.editfyo = uicontrol( ...
            'Parent', handles.uipanel1, ...
            'Tag', 'editfyo', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', [64 7 11 1.61538461538462], ...
            'FontName', 'Times New Roman', ...
            'FontSize', 12, ...
            'BackgroundColor', [1 1 1], ...
            'String', '486.0', ...
            'Callback', @editfyo_Callback, ...
            'CreateFcn', @editfyo_CreateFcn);
        
        handles.editfyi = uicontrol( ...
            'Parent', handles.uipanel1, ...
            'Tag', 'editfyi', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', [64 4 11 1.61538461538462], ...
            'FontName', 'Times New Roman', ...
            'FontSize', 12, ...
            'BackgroundColor', [1 1 1], ...
            'String', '470.0', ...
            'Callback', @editfyi_Callback, ...
            'CreateFcn', @editfyi_CreateFcn);
        
        handles.editfc = uicontrol( ...
            'Parent', handles.uipanel1, ...
            'Tag', 'editfc', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', [64 1 11 1.61538461538462], ...
            'FontName', 'Times New Roman', ...
            'FontSize', 12, ...
            'BackgroundColor', [1 1 1], ...
            'String', '46.2', ...
            'Callback', @editfc_Callback, ...
            'CreateFcn', @editfc_CreateFcn);
        
        handles.editPu_ABC = uicontrol( ...
            'Parent', handles.uipanel2, ...
            'Tag', 'editPu', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', [11 9.5 13 1.6], ...
            'FontName', 'Times New Roman', ...
            'FontSize', 12, ...
            'BackgroundColor', [1 1 1], ...
            'String', '', ...
            'Callback', @editPu_ABC_Callback, ...
            'CreateFcn', @editPu_ABC_CreateFcn);
        
        handles.editPu_TLBO = uicontrol( ...
            'Parent', handles.uipanel2, ...
            'Tag', 'editPu', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', [44 9.5 13 1.6], ...
            'FontName', 'Times New Roman', ...
            'FontSize', 12, ...
            'BackgroundColor', [1 1 1], ...
            'String', '', ...
            'Callback', @editPu_TLBO_Callback, ...
            'CreateFcn', @editPu_TLBO_CreateFcn);
        
        imgData = imread('ANN1.jpg');
        handles.ANNimage = uicontrol( ...
            'CData',imgData, ...
            'Position', [10 13 450 558], ...
            'style','pushbutton',...
            'Parent', handles.figure1);
        
        
    end

%% ---------------------------------------------------------------------------
    function Prediction_ABC_ANN_Callback(hObject,evendata) %#ok<INUSD>
        
        % access L
        L=str2double(handles.editL.String);
        % access DiDo
        DiDo=str2double(handles.editDiDo.String);
        % access tito
        tito=str2double(handles.edittito.String);
        % access Di
        Di=str2double(handles.editDi.String);
        % access ti
        ti=str2double(handles.editti.String);
        % access fyo
        fyo=str2double(handles.editfyo.String);
        % access fyi
        fyi=str2double(handles.editfyi.String);
        % access fc
        fc=str2double(handles.editfc.String);
        
        % Do calculations
        % Input and output data for training the neural network
        load xlsVar.mat M
        M(:,2)=M(:,4)./M(:,2);
        M(:,3)=M(:,5)./M(:,3);
        
        xtrn=zscore(M(:,1:8),0,1)';
        Cxtrn=mean(M(:,1:8),1)';
        Sxtrn=std(M(:,1:8),0,1)';
        ttrn=zscore(M(:,9),0,1)';
        Cttrn=mean(M(:,9),1)';
        Sttrn=std(M(:,9),0,1)';
        % A model is considered as the best when has the smallest RMSE and the
        % largest VAF and R2.
        load optNet_abc.mat net
        % Evaluate the outputs based on the given weights and biases vector
        x=([L;DiDo;tito;Di;ti;fyo;fyi;fc]-Cxtrn)./Sxtrn;
        y = net(x,nn7);
        % Set the 'Pu' editbox to display result.
        set(handles.editPu_ABC,'str',y*Sttrn+Cttrn);
        
    end


    function Prediction_TLBO_ANN_Callback(hObject,evendata) %#ok<INUSD>
        
        % access L
        L=str2double(handles.editL.String);
        % access DiDo
        DiDo=str2double(handles.editDiDo.String);
        % access tito
        tito=str2double(handles.edittito.String);
        % access Di
        Di=str2double(handles.editDi.String);
        % access ti
        ti=str2double(handles.editti.String);
        % access fyo
        fyo=str2double(handles.editfyo.String);
        % access fyi
        fyi=str2double(handles.editfyi.String);
        % access fc
        fc=str2double(handles.editfc.String);
        
        % Do calculations
        % Input and output data for training the neural network
        load xlsVar.mat M
        M(:,2)=M(:,4)./M(:,2);
        M(:,3)=M(:,5)./M(:,3);
        
        xtrn=zscore(M(:,1:8),0,1)';
        Cxtrn=mean(M(:,1:8),1)';
        Sxtrn=std(M(:,1:8),0,1)';
        ttrn=zscore(M(:,9),0,1)';
        Cttrn=mean(M(:,9),1)';
        Sttrn=std(M(:,9),0,1)';
        % A model is considered as the best when has the smallest RMSE and the
        % largest VAF and R2.
        load optNet_tlbo.mat net
        % Evaluate the outputs based on the given weights and biases vector
        x=([L;DiDo;tito;Di;ti;fyo;fyi;fc]-Cxtrn)./Sxtrn;
        y = net(x,nn7);
        % Set the 'Pu' editbox to display result.
        set(handles.editPu_TLBO,'str',y*Sttrn+Cttrn);
        
    end


%% ---------------------------------------------------------------------------
    function editfc_Callback(hObject,evendata) %#ok<INUSD>
        
    end

%% ---------------------------------------------------------------------------
    function editfc_CreateFcn(hObject,evendata) %#ok<INUSD>
        
    end

%% ---------------------------------------------------------------------------
    function editL_Callback(hObject,evendata) %#ok<INUSD>
        
    end

%% ---------------------------------------------------------------------------
    function editL_CreateFcn(hObject,evendata) %#ok<INUSD>
        
    end

%% ---------------------------------------------------------------------------
    function editPu_ABC_Callback(hObject,evendata) %#ok<INUSD>
        
    end

%% ---------------------------------------------------------------------------
    function editPu_ABC_CreateFcn(hObject,evendata) %#ok<INUSD>
        
    end

%% ---------------------------------------------------------------------------
    function editPu_TLBO_Callback(hObject,evendata) %#ok<INUSD>
        
    end

%% ---------------------------------------------------------------------------
    function editPu_TLBO_CreateFcn(hObject,evendata) %#ok<INUSD>
        
    end

%% ---------------------------------------------------------------------------
    function editfyo_Callback(hObject,evendata) %#ok<INUSD>
        
    end

%% ---------------------------------------------------------------------------
    function editfyo_CreateFcn(hObject,evendata) %#ok<INUSD>
        
    end

%% ---------------------------------------------------------------------------
    function edittito_Callback(hObject,evendata) %#ok<INUSD>
        
    end

%% ---------------------------------------------------------------------------
    function edittito_CreateFcn(hObject,evendata) %#ok<INUSD>
        
    end

%% ---------------------------------------------------------------------------
    function editti_Callback(hObject,evendata) %#ok<INUSD>
        
    end

%% ---------------------------------------------------------------------------
    function editti_CreateFcn(hObject,evendata) %#ok<INUSD>
        
    end

%% ---------------------------------------------------------------------------
    function editfyi_Callback(hObject,evendata) %#ok<INUSD>
        
    end

%% ---------------------------------------------------------------------------
    function editfyi_CreateFcn(hObject,evendata) %#ok<INUSD>
        
    end

%% ---------------------------------------------------------------------------
    function edit1_Callback(hObject,evendata) %#ok<INUSD>
        
    end

%% ---------------------------------------------------------------------------
    function edit1_CreateFcn(hObject,evendata) %#ok<INUSD>
        
    end

%% ---------------------------------------------------------------------------
    function editDiDo_Callback(hObject,evendata) %#ok<INUSD>
        
    end

%% ---------------------------------------------------------------------------
    function editDiDo_CreateFcn(hObject,evendata) %#ok<INUSD>
        
    end

%% ---------------------------------------------------------------------------
    function editDi_Callback(hObject,evendata) %#ok<INUSD>
        
    end

%% ---------------------------------------------------------------------------
    function editDi_CreateFcn(hObject,evendata) %#ok<INUSD>
        
    end

end
